sudo: required
dist: trusty

language: python

env:
  matrix:
    - TEST_SUITE=lint
    - TEST_SUITE=pycodestyle
    - TEST_SUITE=unit-tests
    - TEST_SUITE=tests
    - TEST_SUITE=mypy
    - TEST_SUITE=doclint

python:
  #- "2.7"
  #- "3.4"
  - "3.5"
  #- "3.5-dev" # 3.5 development branch
  #- "nightly" # currently points to 3.6-dev

# commands to install dependencies
before_install:
  - sudo apt-get install libtcmalloc-minimal4
  - export LD_PRELOAD="/usr/lib/libtcmalloc_minimal.so.4"
  - pip install -r requirements.txt
  - if [ -f tests/$TEST_SUITE""_requirements.txt ]; then pip install -r tests/$TEST_SUITE""_requirements.txt; fi
  - if [ -f tests/$TEST_SUITE""_install.sh ]; then tests/$TEST_SUITE""_install.sh; fi

# command to run tests
script: tests/$TEST_SUITE""_run.sh
