sudo: required
dist: trusty

language: python

env:
  global:
    - TF=0.11.0-cp35-cp35m
  matrix:
    - TEST_SUITE=lint
    - TEST_SUITE=unit-tests
    - TEST_SUITE=tests
    - TEST_SUITE=mypy

python:
  #- "2.7"
  #- "3.4"
  - "3.5"
  #- "3.5-dev" # 3.5 development branch
  #- "nightly" # currently points to 3.6-dev

# commands to install dependencies
before_install:
  - pip install -r requirements.txt
  - pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-$TF""-linux_x86_64.whl
  - if [ -f tests/$TEST_SUITE""_requirements.txt ]; then pip install -r tests/$TEST_SUITE""_requirements.txt; fi

# command to run tests
script: tests/$TEST_SUITE""_run.sh
